ruby '2.1.5'

source 'https://rubygems.org'

gem 'sinatra'
gem 'erubis'
gem 'thin'
gem 'net-ssh'

gem 'rb-fsevent', '~> 0.9'
gem 'rack-livereload'
gem 'guard-livereload'
gem 'rake-pipeline'
gem 'rake-pipeline-web-filters'
gem 'coffee-script'
gem 'yui-compressor'
gem 'uglifier'
gem 'sass'
gem 'compass'
gem 'foreman'
gem 'mina'
gem 'therubyracer'
